### ISSUE TITLE
"Sync Successful" après erreur en mid-deploy

### ISSUE THREAD

**Issue by mathroc** [ezweb/git-up#18]
si la dernière commande du hook `mid-deploy` renvoit un code d'erreur, la synchro n'est pas faite (entre varan02 et les autres serveurs) mais le message "Sync Successful" apparait

note: la notification newrelic et le "REPORT HOOK" sont exécuté aussi alors qu'ils ne devraient peut-être pas

**Comment by mathroc** [comment]
bug toujours d'actualité !

**Comment by gregorg** [comment]
C'est normal: le hook "mid-deploy" est exécuté avant le "Sync Successful". Faut-il abandonner la synchro si le hook mid échoue ? J'en suis pas certain :-/

**Comment by mathroc** [comment]
si je me souviens bien, justement, la synchro n'est faite que sur varan02 (varan22 maintenant) et pas sur les autres. à vérifier

par contre, je me suis trompé, c'est #17 que je voulais "up-er"

**Comment by gregorg** [comment]
#17 is closed.

Donc, je suis vraiment pas certains que ce soit une bonne chose d'annuler un déploiement si le hook plante.
